### ISSUE TITLE
Question: Pixel manipulation and alpha

### ISSUE THREAD

**Issue by ErikNatanael** [turnage/valora#41]
Hi!
I don't know if this is where you want to keep discussions, feel free to delete.
I've been implementing [Anders Hoff's DOF technique](https://inconvergent.net/2019/depth-of-field/) in valora as a starting project, but I can't find any pixel manipulation tools. Is there a way to directly set pixels on the canvas other than a line to 1 pixel away? The main issue I'm running into is that the technique require a very large number of samples at very low alpha, and using alpha values that low (e.g. 0.001) the colour never reaches full brightness. A solution would be to create my own array of brightness values and draw them as pixels.

MVP of low alpha:
```
use valora::prelude::*;

fn main() -> Result<()> {
    run_fn(Options::from_args(), |_gpu, world, _rng| {
        Ok(move |ctx: Context, canvas: &mut Canvas| {
            canvas.set_color_alpha(LinSrgb::new(1., 1., 1.), 0.001);
            canvas.paint(Filled(ctx.world));
        })
    })
}
```

Or perhaps this is simply not the intended use case for the framework.
Cheers!

**Comment by turnage** [comment]
I do intend to add a more ergonomic API for this.

At the moment, the only methods are:

1. create a glium Texture2D and use it as a uniform in a shader.

Or

2. A 1 pixel Ngon::square

I’m not sure a line to 1 pixel away will work; the lines don’t directly go
to the hardware rasterizer. They pass through Lyon first. I haven’t tried
that.

**Comment by turnage** [comment]
As for the low alpha values, those values are passed directly to the GPU
and end up being the fragment shader output.

You’ve discovered a bug actually. I meant to store those results in a
Float32 texture. When rendering to screen though, it uses whatever the
platform defaults to which is usually an integer buffer.

If you render to file, you should see the low alphas accumulate. Valora
should render to the intermediate buffer first and then blit to screen for
the on-screen preview window.

**Comment by ErikNatanael** [comment]
Ahh yes of course a 1 pixel square should be better. The lines seem to do the trick as well though.
I'll give rendering to file a try then, thanks!

**Comment by turnage** [comment]
I redirected rendering to an intermediate buffer to accumulate alpha before drawing to screen in the linked commit. I think the rest of this issue is covered in #37.
